package com.csi.threads;


class Thread6 extends Thread{
	
}
public class ThreadConcept6 {
	public static void main(String[] args) {
		//System.out.println( Thread6.currentThread().getName()	);//It shows which Thread is present"Main"
	/*	Thread6 t= new Thread6();
		System.out.println( t.getName()  ); 	//Thread Name is Thread-0 it is generated by JVM
	}
	{Thread6 t= new Thread6();
	System.out.println( t.getName()  );*/
		Thread6.currentThread().setName("ThreadName Jyoti");
		System.out.println( Thread6.currentThread().getName()	);// we can also set the the thread name by programmer.
	}	
}